// src/lib/constants/notes.ar.ts
import type { NoteKey } from "./notes.en";

export const NOTE_LABELS_AR: Record<NoteKey, string> = {
  rhubarb: "راوند",
  red_apple: "تفاح أحمر",
  green_apple: "تفاح أخضر",
  peach: "خوخ",
  plum: "برقوق",
  lychee: "ليتشي",
  cherry: "كرز",
  blackberry: "توت أسود",
  fig: "تين",
  red_currant: "كشمش أحمر",
  black_currant: "كشمش أسود",
  pineapple: "أناناس",
  pink_pepper: "فلفل وردي",
  raspberry: "توت العليق",
  strawberry: "فراولة",
  pear: "كمثرى",

  lemon: "ليمون",
  bergamot: "برغموت",
  verbena: "لويزة",
  mandarin: "يوسفي",
  lime: "ليمون أخضر",
  yuzu: "يوزو",
  grapefruit: "جريب فروت",
  orange: "برتقال",

  biscuit: "بسكويت",
  honey: "عسل",
  cream: "كريمة",
  caramel: "كراميل",
  almond: "لوز",
  chocolate: "شوكولاتة",
  praline: "برالين",
  coconut: "جوز الهند",
  nutmeg: "جوزة الطيب",
  chestnut: "كستناء",
  hazelnut: "بندق",
  pistachio: "فستق",
  ice_cream: "آيس كريم",
  milk: "حليب",
  marshmallow: "مارشميلو",
  cacao: "كاكاو",

  mastic: "مستك",
  amber: "عنبر",
  tobacco: "تبغ",
  frankincense: "لبان",
  spices: "توابل",
  vanilla: "فانيلا",
  coffee: "قهوة",
  tonka_bean: "تونكا",
  ginger: "زنجبيل",
  cardamom: "هيل",
  black_tea: "شاي أسود",
  coriander: "كزبرة",
  pepper: "فلفل",
  cinnamon: "قرفة",
  saffron: "زعفران",

  sage: "مريمية",
  rosemary: "إكليل الجبل",
  basil: "ريحان",
  wormwood: "شيح",
  sea: "بحر",
  salt: "ملح",
  green_tea: "شاي أخضر",
  mint: "نعناع",
  // P1 #14 — Chemical notes with contextual descriptions
  ambroxan: "أمبروكسان (عنبر صناعي)",
  aldehydes: "ألدهيد (رائحة صابونية)",

  guaiac_wood: "جاياك",
  sandalwood: "صندل",
  cedar: "أرز",
  oud: "عود",
  oakmoss: "طحلب البلوط",
  lavender: "لافندر",
  vetiver: "فيتيفر",
  patchouli: "باتشول",
  cashmeran: "كاشمران (دفء مخملي)",
  leather: "جلد",

  // P0 #1.5 — Essential notes that were missing
  rose: "ورد",
  jasmine: "ياسمين",
  musk: "مسك",
  iris: "سوسن",
  violet: "بنفسج",
  neroli: "زهر النارنج",
  tuberose: "مسك الليل",
  benzoin: "جاوي",

  // P1 #21 — Gulf-specific notes
  taif_rose: "ورد الطائف",
  incense: "بخور",
  white_musk: "مسك أبيض",
  ambergris: "عنبر بحري",
  dahn_al_oud: "دهن العود",
};
